# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Generate screenshots"
  lane :screenshots do
    capture_screenshots(
      languages: ["en-US"],
      devices: [
        "iPhone SE (3rd generation)",        # Home Button iPhone
        "iPhone 13",                         # Notch iPhone
        "iPhone 15 Pro Max",                 # Dynamic Island iPhone
        "iPad (9th generation)",             # iPad with Home Button
        "iPad Pro (12.9-inch) (6th generation)"  # iPad without Home Button
      ],
      scheme: "AppUITests",  # Replace with your UITest scheme name
      clean: true,
      erase_simulator: true,
      output_directory: "fastlane/screenshots"
    )
  end
end
